### PR TITLE
Make the build script support Windows and BSD

### PR DESCRIPTION
**Pull request by flanfly**
This extends the build script to use the `cmake` crate to build the native extension. On Windows it will be build with MSVC. The PR also gets rid of the `build_lib.sh` and adds `DOtherSide` as git submodule.

### CODE REVIEW

**Comment by White-Oak** [comment]
@flanfly This is incredible! 

Could it be, that the build failing due to the old gcc on CI? It is `4.8` there.

**Comment by flanfly** [comment]
I copied half of the code off the `qmlrs` project, so kudos to them. DOtherSide seems to require gcc 4.9 now. The `.travis` file should work now.

**Review by White-Oak — APPROVED** [review]

**Comment by White-Oak** [comment]
@flanfly if this is ready for merging, I can merge it.

Thanks for all the work.

**Comment by flanfly** [comment]
Ready

**Pull request merged**
