### PR TITLE
added FreeBSD compilation support to build.rs

### PR DESCRIPTION
**Pull request by fneddy**
1. renamed stdc++ to c++
2. added /usr/local/lib/ to ld path
3. added freebsd to use version nummer in lib name

### CODE REVIEW

**Comment by berlineddy** [comment]
has somebody tried qml-rust on windows, dragonfly, android, ... ?

**Comment by White-Oak** [comment]
I guess BSD support was added in #30

**Comment by fneddy** [comment]
ahh, I see.

that's a much nicer solution, but sill one line is missing :)

**Comment by White-Oak** [comment]
@fneddy thanks

**Pull request merged**
