### PR TITLE
Send out notification on changed property.

### PR DESCRIPTION
**Pull request by vandenoever**
It seems like this was missing.

### CODE REVIEW

**Review by White-Oak — COMMENTED** [review]
Well, I remember my confusion over this. It's seems right this way, but I was a bit confused by qt documentation, where code for properties called notify signals on its own. http://doc.qt.io/qt-5/properties.html look for `void setPriority(Priority priority)`

**Comment by vandenoever** [comment]
The C++ implementation example has calls the `notify` function in the `write` function:

```C++
    void setPriority(Priority priority)
    {
        m_priority = priority;
        emit priorityChanged(priority);
    }
```

In the documentation for `NOTIFY` it says: "The NOTIFY signal should only be emitted when the property has really been changed, to avoid bindings being unnecessarily re-evaluated in QML, for example. ". So what's also missing is a check to see if the value actually changed.

**Comment by vandenoever** [comment]
Is there something needed to get this merged?

**Comment by White-Oak** [comment]
@vandenoever from your comment:

> In the documentation for NOTIFY it says: "The NOTIFY signal should only be emitted when the property has really been changed, to avoid bindings being unnecessarily re-evaluated in QML, for example. ". So what's also missing is a check to see if the value actually changed.

**Comment by vandenoever** [comment]
The code now checks if the value was changed.

**Comment by cortex** [comment]
I would love to see this merged! I just got started porting some qml stuff I have from Go. I was confused for a long time why my property changes didn't work, and how I should communicate with my components if this wasn't possible. With this branch, this aspect of my code works great!

**Comment by vandenoever** [comment]
Still hope this gets merged at some point.

**Comment by apopiak** [comment]
What's up with this PR @White-Oak ?

**Pull request closed without merging**
